language: go

sudo: false

matrix:
  include:
    - go: 1.x
      env:
        - RELEASE=true
        - GO111MODULE=on
    - go: master
      env:
        - RELEASE=false
        - GO111MODULE=on
  allow_failures:
    - go: master

after_success:
  - go build -ldflags="-s -w"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aOP3anMYp76Siz4PYnl5iqw3Wa0sJ+DCyveXc71gigCOgSyK9SARlolkX/4hzrvpJvKUiQVlCXTTUDFYD6THz3aQeQY1P8+GuhN2+ymh5abtfk4aaGwqfQsBaaDCZKcYDddAfWW25qVS15owqpSM9aXqAu8CM7kQjJIj71yWen8l/TFSres3XTBpuWy1CjUiMw16f7Uyiv8OH5KMor6qghbkNc3uwA1o2MRj+PZ22ZA5L0dIFa9lgOIntys7IoQEruCZ484nb6JxM1HB2uA+JXJJ8sZNhxhwPHqm/5JvyQ7WvPJEWxUH0E8sbNZ7w5lEmtjUYNvCuvQJEPZAqkcs9g2m7WrhYK1BPdxA8BVxg2+YzDFGVMOKq0kD2delX1Y8J/uQlcKja9gbsnoLXwBp9XfYjcSDshSdBxK3qsVMuB9roCiVB13b+W3xTlvMzczbI9ayTFJJVMA2ohDQR1LxDw0C4wUoteopk15PykVSdCoEDMZhrSBWHZlfDs1dxZBBoI5iyeKR36JDE+6vAWlDSgVflYsansdukYcd9OQjJMtgJ8xDucYrVUWRR9DNQE5ENuxIVW9b1OPYCEbfc+ewRrzjATKxUOy/vIQ2xOKsCY+YaGbi76EKU7VRGCc7Kj4u0CvXUf1uMKXQXJaG+PugE5nYDFiVBbjNbTnPLUeoVPI=
  file: go-smartmail
  on:
    tags: true
    repo: mback2k/go-smartmail
    condition: $RELEASE = true
